name: Auto Merge PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PR Status
        id: check_pr
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const approved = pr.reviews.some(review => review.state === 'APPROVED');
            const reviewed = pr.reviews.length > 0;
            const mergeable = pr.mergeable;

            console.log(`PR ${pr.number} - Approved: ${approved}, Reviewed: ${reviewed}, Mergeable: ${mergeable}`);

            return {
              should_merge: approved && reviewed && mergeable
            };

      - name: Merge PR
        if: steps.check_pr.outputs.should_merge == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
