name: Auto Merge Branches

on:
  push:
    branches:
      - 'profit_dep_hf_*'
      - 'profit_dep_minor_*'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
    - name: Run auto merge script
      env:
        JEGANTOKEN: ${{ secrets.JEGANTOKEN }}
      run: |
        #!/usr/bin/env bash
        set -o pipefail

        # Configuration
        REPO_URL="https://github.com/egangithub1502/Jegan-Raja"
        GH_TOKEN="${JEGANTOKEN}"

        # Functions
        function fetch_branch() {
          local pattern=$1
          git branch -r | grep "origin/$pattern" | tail -n 1 | sed 's|origin/||' | xargs
        }

        # Main Script
        # Step 1: Check out the repo and set up Git
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git clone "$REPO_URL" repo
        cd repo || exit

        # Step 2: Handle profit_dep_hf to profit_dep_minor merge
        if [[ "$GITHUB_REF" == refs/heads/profit_dep_hf_* ]]; then
          MINOR_BRANCH=$(fetch_branch 'profit_dep_minor_')
          if [[ -z "$MINOR_BRANCH" ]]; then
            echo "No minor branch found. Exiting."
            exit 1
          fi
          echo "Found minor branch: $MINOR_BRANCH"
          
          git checkout "$MINOR_BRANCH"
          git fetch origin
          
          HF_BRANCH="${GITHUB_REF#refs/heads/}"
          echo "Merging $HF_BRANCH into $MINOR_BRANCH"
          git merge --no-ff "$HF_BRANCH"
          
          if [[ $? -ne 0 ]]; then
            TEMP_BRANCH="temp/hf-to-minor-$(date +%s)"
            git checkout -b "$TEMP_BRANCH"
            git push origin "$TEMP_BRANCH"
            echo "Conflict detected. Temporary branch created: $TEMP_BRANCH"
            exit 1
          else
            git push origin "$MINOR_BRANCH"
          fi
        fi

        # Step 3: Handle profit_dep_minor to master merge
        if [[ "$GITHUB_REF" == refs/heads/profit_dep_minor_* ]] || [[ "$GITHUB_REF" == refs/heads/profit_dep_hf_* ]]; then
          git checkout master
          git fetch origin
          
          MINOR_BRANCH=$(fetch_branch 'profit_dep_minor_')
          if [[ -z "$MINOR_BRANCH" ]]; then
            echo "No minor branch found. Exiting."
            exit 1
          fi
          echo "Found minor branch: $MINOR_BRANCH"
          
          git merge --no-ff "$MINOR_BRANCH"
          
          if [[ $? -ne 0 ]]; then
            TEMP_BRANCH="temp/minor-to-master-$(date +%s)"
            git checkout -b "$TEMP_BRANCH"
            git push origin "$TEMP_BRANCH"
            echo "Conflict detected. Temporary branch created: $TEMP_BRANCH"
            exit 1
          else
            git push origin master
          fi
        fi
      shell: bash
