name: Auto Merge

on:
  pull_request:
    types: [review_requested, reviewed]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install gh

    - name: Authenticate GitHub CLI
      run: echo "${{ secrets.JEGANTOKEN }}" | gh auth login --with-token

    - name: Check pull request review status
      id: check_reviews
      run: |
        pr_number=${{ github.event.pull_request.number }}
        review_status=$(gh pr view $pr_number --json reviews --jq '.reviews[] | select(.state == "APPROVED")' || echo "")
        
        if [ -z "$review_status" ]; then
          echo "No approved reviews yet."
          exit 1
        fi

    - name: Merge pull request
      if: success()
      run: |
        pr_number=${{ github.event.pull_request.number }}
        gh pr merge $pr_number --merge --admin
