name: Automerge if conditions are met

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PR conditions
        id: check_conditions
        uses: actions/github-script@v6
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            const isApproved = reviews.data.some(review => review.state === 'APPROVED');
            const isReviewed = reviews.data.length > 0;
            const assignedUsers = pr.data.assignees.map(a => a.login);
            const commonUser = 'egangithub1502';
            
            console.log(`isApproved: ${isApproved}`);
            console.log(`isReviewed: ${isReviewed}`);
            console.log(`assignedUsers: ${assignedUsers}`);
            
            if (isApproved && isReviewed && assignedUsers.includes(commonUser)) {
              core.setOutput('merge', 'true');
            } else {
              core.setOutput('merge', 'false');
            }
          github-token: ${{ secrets.JEGANTOKEN }}

      - name: Debug Output
        run: echo "Merge Output: ${{ steps.check_conditions.outputs.merge }}"

      - name: Merge PR
        if: steps.check_conditions.outputs.merge == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              commit_message: 'Automerge by GitHub Actions'
            });
            console.log('Pull request merged');
          github-token: ${{ secrets.JEGANTOKEN }}
