name: Automerge if conditions are met

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            const isApproved = reviews.data.some(review => review.state === 'APPROVED');
            const isReviewed = reviews.data.length > 0;
            const assignedUsers = pr.data.assignees.map(a => a.login);
            const commonUser = 'egangithub1502';
            
            if (isApproved && isReviewed && assignedUsers.includes(commonUser)) {
              return true;  # Triggers merge
            } else {
              return false; # Does nothing
            }
          github-token: ${{ secrets.JEGANTOKEN }}  # Assuming a PAT with necessary permissions
          debug: true
          user-agent: actions/github-script
          result-encoding: json
          retries: 0
          retry-exempt-status-codes: 400,401,403,404,422
